### ISSUE TITLE
After running script, lineups are not set

### ISSUE THREAD

**Issue by devinmcinnis** [devinmcinnis/yahoo-fantasy-start-active-players#2]
I have noticed that I have to run the script twice (sometimes three times) to get the rosters to set properly. It was also [pointed out](https://gist.github.com/devinmcinnis/8109488#gistcomment-1590312) on the old gist.  I'm not sure what's causing this to happen :confused:

**Comment by burnSMACKER** [comment]
The code seems to only be setting up lineups 5 days ahead of the current date.
