### ISSUE TITLE
New issue, doesn't seem to work anymore

### ISSUE THREAD

**Issue by yawrey** [devinmcinnis/yahoo-fantasy-start-active-players#7]
Hey man, thank you so much for doing this. I used your code a couple months ago and since then I've made changes to my team so I needed to use it again today. Here's the message I got. 

Failed to load https://login.yahoo.com/config/login?.src=spt&.intl=us&.done=https%3A%2F%2Fhockey.fantasysports.yahoo.com%2Fhockey%2F41843%2F7%2Fstartactiveplayers%3Fdate%3D2018-01-19%26crumb%3DrtcQ%252FaO5XLE%26.scrumb%3D0&specId=usernameRegWithName: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://hockey.fantasysports.yahoo.com' is therefore not allowed access.

Did I do something wrong? 
Cheers
Yawrey

**Comment by devinmcinnis** [comment]
Thanks :) 

I just tested and it set my lineups so I'm wondering if your cookie has expired. Can you try setting one of your players and refreshing the page to confirm it works then re-run this script. 

Also, make sure you're running the script on your My Team page.

**Comment by yawrey** [comment]
Cleared cookies, good as new. Cheers!
